# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "69214bb55fd1f557ec4107a510bacc1c"
name = "md-pin"
handle = "md-pin"
application_url = "https://lenders-cycling-styles-faculty.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-b6d360b8.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://lenders-cycling-styles-faculty.trycloudflare.com/auth/callback",
  "https://lenders-cycling-styles-faculty.trycloudflare.com/auth/shopify/callback",
  "https://lenders-cycling-styles-faculty.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
