export const fontList = [
  "Helvetica Neue",
  "Arial",
  "Georgia",
  "Grechen Fuemen",
  "Times New Roman",
  "Courier New",
  "Trebuchet MS",
  "Verdana",
  "Noto Sans",
  "Noto Serif",
  "Noto Mono",
  "Noto Sans JP",
  "Noto Serif JP",
  "Noto Sans KR",
  "Noto Serif KR",
  "Noto Sans SC",
  "Noto Serif SC",
  "Noto Sans TC",
  "Noto Serif TC",
  "Lato",
  "Playfair Display",
  "Merriweather",
  "Montserrat",
  "Raleway",
  "Roboto",
  "Source Sans Pro",
  "Open Sans",
  "PT Sans",
  "PT Serif",
  "Droid Sans",
  "Droid Serif",
  "Quicksand",
  "Poppins",
  "Oswald",
];

export const fontSizes = [
  10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 36, 40, 42, 48, 54, 56, 60,
  64, 72, 80, 96, 108, 120, 144, 168, 192, 216, 174,
];
