const styles = {
  theme_button: {
    background: "rgba(215, 44, 13, 1)",
    color: "white",
    border: "none",
    padding: "10px 40px",
    cursor: "pointer",
    borderRadius: "4px",
    minWidth: "150px",
  },
  theme_button_light: {
    background: "white",
    border: "1px solid rgba(0, 0, 0, 0.05)",
    borderColor: "#d72c0d",
    color: "black",
    padding: "10px 40px",
    cursor: "pointer",
    borderRadius: "4px",
    minWidth: "150px",
  },
  theme_button_2: {
    background: "white",
    color: "black",
    border: "1px solid gainsboro",
    padding: "10px 40px",
    cursor: "pointer",
    borderRadius: "4px",
    minWidth: "150px",
  },
  create_checklist_ul_li: {
    marginBottom: "10px",
  },
  style_pin_title_s_items_container: {
    padding: "5px",
    background: "white",
    borderRadius: "7px",
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
  },
  style_pin_title_s_items_fontsize_select: {
    outline: "none",
    border: "none",
    width: "45px",
  },
  style_pin_title_s_items_fontfamily_select: {
    outline: "none",
    border: "none",
    width: "145px",
  },
  style_pin_title_s_items_color_select: {
    border: "none",
    outline: "none",
    padding: "0px",
    width: "25px",
    paddingTop: "0px",
    margin: "0",
    background: "none",
  },
  toolbarContainer: {
    display: "flex",
    flexDirection: "column",
    padding: "10px",
    backgroundColor: "#f4f4f4",
    borderRadius: "8px",
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1)",
    width: "250px",
  },
  section: {
    marginBottom: "20px",
  },
  toolbarTitle: {
    fontSize: "18px",
    marginBottom: "10px",
    fontWeight: "bold",
    color: "#333",
  },
  selectContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  fontSizeSelect: {
    padding: "8px",
    fontSize: "14px",
    borderRadius: "4px",
    border: "1px solid #ccc",
    backgroundColor: "#fff",
    display: "none",
  },
  fontFamilySelect: {
    padding: "8px",
    fontSize: "14px",
    borderRadius: "4px",
    border: "1px solid #ccc",
    backgroundColor: "#fff",
  },
  buttonContainer: {
    display: "flex",
    gap: "10px",
    marginBottom: "10px",
  },
  iconButton: {
    padding: "8px 12px",
    fontSize: "16px",
    borderRadius: "4px",
    border: "1px solid #ccc",
    backgroundColor: "transparent",
    cursor: "pointer",
    transition: "background-color 0.3s",
  },
  alignmentContainer: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "10px",
  },
  alignLabel: {
    fontSize: "14px",
    color: "#333",
  },
  alignSelect: {
    padding: "8px",
    fontSize: "14px",
    borderRadius: "4px",
    border: "1px solid #ccc",
    backgroundColor: "#fff",
  },
  fontColorContainer: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  colorLabel: {
    fontSize: "14px",
    color: "#333",
  },
  colorPicker: {
    width: "30px",
    height: "30px",
    border: "none",
    cursor: "pointer",
  },
  opacitySlider: {
    width: "200px", // Increased width for better control
    height: "10px", // Increased height for better grip
    cursor: "pointer",
    appearance: "none",
    background: "#ddd",
    borderRadius: "5px",
    outline: "none",
    transition: "0.2s",
  },
  fontSizeInputContainer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  fontSizeButton: {
    padding: "8px",
    fontSize: "1.25rem",
    cursor: "pointer",
    border: "1px solid #ccc",
    background: "#f0f0f0",
    borderRadius: "4px",
    textAlign: "center",
  },
  fontSizeInput: {
    width: "100%",
    textAlign: "center",
    padding: "6px",
    fontSize: "1rem",
    border: "1px solid #ccc",
    borderRadius: "4px",
  },
};
export default styles;
